import { Dimensions, StyleSheet } from "react-native";
import deviceInfoModule from "react-native-device-info";
import colors from "../../assets/color/colors";

const windowWidth = Dimensions.get("window").width;
let version = deviceInfoModule.getSystemVersion;
const style = StyleSheet.create({
  starView:{
    flexDirection: "row",
    justifyContent: "flex-start",
    marginHorizontal: 20,
    marginTop: 10,
    alignItems: "center",
  },
  goldCircle: {
    backgroundColor: colors.gold,
    height: 16,
    width: 16,
    borderRadius: 8,
    textAlign: "center",
  },
  chatImg: {
    height: 35,
    width: 35,
    borderRadius: 17.5,
  },
  chatView: {
    paddingVertical: 5,
    flexDirection: "row",

    width: Dimensions.get("window").width - 40,
    alignItems: "center",
  },
  circleImg: { width: 40, height: 40, borderRadius: 20 },
  onlineImg: {
    backgroundColor: colors.green,
    width: 12,
    height: 12,
    position: "absolute",
    left: 30,
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 6,
    zIndex: 100,
    bottom: 4,
  },
  smallcircle: {
    backgroundColor: colors.red,
    width: 12,
    height: 12,
    position: "absolute",
    left: 30,
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 6,
    zIndex: 100,
  },
  onlineView: { height: 45, width: 45 },
  desc: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  descView: {
    // flexDirection: "column",
    paddingHorizontal: 20,
    paddingRight: 20,
  },
  notificationImg: {
    height: 35,
    width: 35,
    borderRadius: 17.5,
  },
  notificationView: {
    // marginHorizontal: 10,
    backgroundColor: "#fff",
    paddingVertical: 15,
    alignSelf: "flex-start",
    borderBottomColor:colors.lightGray,
    borderBottomWidth:1,
  },
  goldView: {
    backgroundColor: colors.hotPink,
    height: 25,
    width: 25,
    borderRadius: 12.5,
    justifyContent: "center",
    alignItems: "center",
  },
  setting: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: Platform.OS === 'ios' ? 0 : 10,
  },
  pinkBkground: {
    backgroundColor: "rgba(250, 223, 218, 0.6)",
    // width: 300,
    alignSelf: "center",
    marginTop: 10,
    borderRadius: 10,
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginVertical: 10,
    justifyContent: "center",
  },
  appbar: {
    //   marginHorizontal: 20,
    flexDirection: "row",
    padding: 20,
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressGoalView: {
    width: version == 11 ? 375 : 334,
    height: version == 11 ? 275 : 225,
    backgroundColor: colors.white,
    marginVertical: 15,
    // left: '5.5%',
    paddingTop: 15,
    margin: 4,
    // marginBottom: 50,
  },
  logo: {
    width: 40,
    height: 40,
    backgroundColor: colors.black,
    borderRadius: 40 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  logoContent: {
    fontSize: 18,
    color: colors.white,
    fontFamily: "Inter",
  },
  taskTitle: {
    fontFamily: "Inter",
    fontSize: 20,
    color: colors.black,
    fontWeight: "bold",
    lineHeight: 24,
    left: "5%",
    paddingTop: "2.5%",
    textAlign: "left",
  },
  taskMembers: {
    flexDirection: "row",
    left: "7.5%",
    marginTop: "5%",
    alignItems: "center",
  },
  memberImage: {
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
  },
  memberCount: {
    fontSize: 11,
    color: colors.gray,
    letterSpacing: 0.22,
    fontFamily: "Inter",
  },
  buttonsView: {
    flexDirection: "row",
    left: 20,
    marginVertical: 20,
    // alignItems: 'center',
  },
  button: {
    borderRadius: 100,
    borderWidth: 1,
    borderColor: colors.secondary,
    alignSelf: "flex-start",
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  buttonText: {
    fontFamily: "Inter-Bold",
    fontSize: 12,
    alignItems: "center",
    justifyContent: "center",
    color: colors.secondary,
    padding: 10,
    paddingHorizontal: 20,
  },
  thinButtonView: {
    borderRadius: 100,
    alignSelf: "flex-start",
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
    marginLeft: 0,
    padding: 10,
  },
  thinButtonText: {
    fontFamily: "Inter",
    fontSize: 12,

    // padding: 10,
    // paddingLeft: '5%',
    // paddingRight: '5%',
  },
  taskView: {
    width: 49,
    height: 19,
    backgroundColor: colors.julep,
    borderRadius: 1,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
  },
  taskText1: {
    color: colors.white,
    fontSize: 11,
    fontWeight: "bold",
  },
  taskView1: {
    backgroundColor: colors.primary,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    // margin: 4,
    alignSelf: "flex-start",
    height: 30,
    paddingHorizontal: 8,
    marginVertical: 8,
  },
  taskCategory: {
    color: colors.secondary,
    textAlign: "center",
    fontSize: 11,
    fontWeight: "bold",
    // padding: '3.5%',
    // paddingTop: '1.5%',
    // paddingBottom: '1.5%',
    letterSpacing: 0.22,
  },
  libraryView: {
    marginVertical: 20,

    width: version == 11 ? 350 : 302,
    height: version == 11 ? 130 : 108,
    borderColor: colors.lightGray,
    // borderWidth: 0.45,
    shadowColor: "#000",
    shadowOffset: { height: -2, width: 3 },
    shadowOpacity: Platform.OS === "android" ? 0.4 : 0.5,
    // shadowRadius: Platform.OS === "android" ? 10 : 10,
    elevation: Platform.OS === "android" ? 10 : 0,
    borderWidth: 0.001,
    backgroundColor: colors.white,
  },
  libraryImgView: {
    backgroundColor: colors.julep,
    height: version == 11 ? 130 : 108,
    flex: 0.3,
    justifyContent: "center",
    alignItems: "center",
  },
  libraryImg: { width: 50, height: 50 },
  libraryContentView: {
    flex: 0.7,
    //  padding: '5%',
    paddingLeft: "5%",
    paddingRight: "5%",
    justifyContent: "center",
  },
  libraryContent: {
    backgroundColor: colors.primary,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: "5%",
  },
  libraryCategory: {
    fontFamily: "Inter",
    color: colors.secondary,
    fontSize: 11,
    fontWeight: "bold",
    padding: "3%",
    paddingLeft: "7.5%",
    paddingRight: "7.5%",
  },
  libraryTitle: {
    fontSize: 16,
    textAlign: "left",
    fontFamily: "Inter",
    letterSpacing: 0.22,
    fontWeight: "bold",
    color: colors.black,
    paddingTop: 0,
  },
  libraryType: {
    fontSize: 14,
    textAlign: "left",
    fontFamily: "Inter",
    letterSpacing: 0.22,
    color: colors.black,
    paddingVertical: 5,
  },
  boldHeading: {
    fontFamily: "Inter",
    fontSize: 50,
    textAlign: "left",
    letterSpacing: 0.22,
    color: colors.white,
  },
  libraryHeadingView: {
    backgroundColor: colors.julep,
    height: version == 11 ? 130 : 108,
    flex: 0.35,
    justifyContent: "center",
    alignItems: "center",
  },
  InterBold: {},
  announcementContainer: {
    marginTop: "5%",
    marginRight: 10,
    width: 168,
    height: 179,
    // borderWidth: 0.5,
    borderColor: colors.lightGray,
    shadowColor: "#000",
    shadowOffset: { height: -2, width: 3 },
    shadowOpacity: Platform.OS === "android" ? 0.4 : 0.5,
    // shadowRadius: Platform.OS === "android" ? 10 : 10,
    elevation: Platform.OS === "android" ? 10 : 0,
    borderWidth: 0.001,
  },
  innerContainer: {
    width: 168,
    height: 110,
    backgroundColor: colors.lightGold,
    justifyContent: "center",
    alignItems: "center",
  },
  roundedView: {
    backgroundColor: colors.secondary,
    width: 86,
    height: 86,
    borderRadius: 86 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    height: 69,
    backgroundColor: colors.white,
    padding: "7.5%",
    justifyContent: "center",
  },
  title: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: "left",
    fontFamily: "Inter",
    color: colors.black,
    padding: "2.5%",
  },
  time: {
    fontSize: 11,
    lineHeight: 15,
    textAlign: "left",
    fontFamily: "Inter",
    color: colors.lightDark,
    padding: "2.5%",
  },
  discussionContainer: {
    marginRight: 10,
    marginTop: "5%",
    marginLeft: 0,
    width: 248,
    height: 133,
    backgroundColor: colors.lightPink,
    padding: "2.5%",
    justifyContent: "center",
  },
  membersImagesView: {
    flexDirection: "row",
    alignItems: "center",
    padding: "5%",
    left: "2.5%",
  },
  memberImages: {
    width: 26,
    height: 26,
    borderRadius: 26 / 2,
  },
  navContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    right: 20,
    marginVertical: 30,
  },
  colornavContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    margin: 30,
  },
  navContainer2: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "2.5%",
    marginVertical: 10,
  },
  navText: {
    color: colors.secondary,
    fontWeight: "bold",
    textAlign: "right",
    fontSize: 11,
    paddingRight: "2.5%",
  },
  colornavText: {
    color: colors.sistaPink,
    fontWeight: "bold",
    textAlign: "right",
    fontSize: 14,
    paddingRight: "2.5%",
  },

  asgView: {
    marginTop: "2.5%",
    marginBottom: "2.5%",
    // width: 335,
    height: version == 11 ? 140 : 118,
    borderColor: colors.lightGray,
    borderWidth: 0.45,
    shadowColor: "#000",
    shadowOffset: { height: -2, width: 3 },
    shadowOpacity: Platform.OS === "android" ? 0.4 : 0.5,
    // shadowRadius: Platform.OS === "android" ? 10 : 10,
    elevation: Platform.OS === "android" ? 10 : 0,
    borderWidth: 0.001,
    backgroundColor: colors.white,
  },
  asgImgView: {
    height: version == 11 ? 140 : 118,
    flex: 0.3,
    justifyContent: "center",
    alignItems: "center",
  },
  asgContentView: {
    flex: 0.7,
    //  padding: '5%',
    paddingHorizontal: 20,

    justifyContent: "center",
  },
  pdfimg: {
    height: 35,
    width: 30,
    resizeMode: "contain",
  },
  pdfimgwidth: {
    width: "15%",
    alignItems: "center",
    justifyContent: "center",
  },
  pdfnamewidth: {
    width: "85%",
    paddingLeft: "2.5%",
  },
  pdfsize: {
    fontSize: 11,
    textTransform: "uppercase",
    fontWeight: "700",
    color: colors.gray,
  },
  pdfname: {
    fontSize: 11,
    fontFamily: "Inter",
    color: colors.black,
    paddingBottom: "2.5%",
    width: "100%",
  },
  pdfname2: {
    fontSize: 11,
    color: colors.black,
    width: "30%",
  },
  pdfcontainer: {
    borderRadius: 2,
    backgroundColor: colors.white,
    borderRadius: 2,
    shadowColor: colors.lightDark,
    elevation: Platform.OS === "android" ? 2.5 : 0,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: "5%",
    margin: 1,
    paddingVertical: 16,
    width: 320,
    marginRight: 10,
  },
  questionContainer: {
    height: 137,
    // width: 320,
    borderRadius: 2,
    flexDirection: "row",
    alignItems: "flex-start",
    //elevation: 0.1,
    borderWidth: 1,
    borderColor: colors.lightGray,
    marginBottom: "2.5%",
  },
  questionImg: {
    // width: 10,
    marginHorizontal: 20,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 10,
  },
  qImg: {
    width: 42,
    height: 42,
    borderRadius: 42 / 2,
    resizeMode: "cover",
  },
  qContainer: {
    paddingTop: 10,
    width: "70%",
    justifyContent: "center",
  },
  qTitle: {
    fontFamily: "Inter",
    fontSize: 16,
    textAlign: "left",
    textAlignVertical: "bottom",
    letterSpacing: 0.22,
    color: colors.black,
  },
  qText: {
    paddingTop: "5%",
    fontFamily: "Interbook",
    fontSize: 11,
    lineHeight: 15,
    textAlign: "left",
    textAlignVertical: "bottom",
    letterSpacing: 0.22,
    color: colors.black,
  },
  fundingView: {
    marginVertical: 20,
    width: "100%",
    height: 270,
    backgroundColor: colors.white,
    elevation: 2.5,
  },
  topFundingView: {
    height: "45%",
    flexDirection: "row",
  },
  topFundingContent: {
    padding: "2.5%",
    width: "90%",
    justifyContent: "center",
  },
  fundTitle: {
    fontFamily: "Inter",
    fontSize: 16,
    width: "90%",
    padding: "2.5%",
    textAlign: "left",
    color: colors.black,
    letterSpacing: 0.22,
  },
  fundingDeadline: {
    fontFamily: "Inter",
    fontSize: 11,
    lineHeight: 15,
    paddingLeft: "2.5%",
    textAlign: "left",
    color: colors.secondary,
    letterSpacing: 0.22,
  },
  bottomFundingView: { height: "55%", flexDirection: "row" },
  bottomFundingContent: {
    padding: "2.5%",
    width: "85%",
  },
  fundDescription: {
    paddingBottom: "5%",
    fontFamily: "Interbook",
    fontSize: 11,

    color: colors.black,
    letterSpacing: 0.22,
    lineHeight: 15,
    textAlignVertical: "top",
    textAlign: "left",
  },
});
export default style;
